apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mba-modulo4-dev
resources:
  - ../../base
  - configmap.yaml
  - infisical-secret.yaml
  - rabbitmq.yaml
images:
  - name: ghcr.io/douglasdossantos/mba-auth-api
    newTag: dev-6abe0da
  - name: ghcr.io/douglasdossantos/mba-aluno-api
    newTag: dev-6abe0da
  - name: ghcr.io/douglasdossantos/mba-bff-api
    newTag: dev-6abe0da
  - name: ghcr.io/douglasdossantos/mba-conteudo-api
    newTag: dev-6abe0da
  - name: ghcr.io/douglasdossantos/mba-pagamentos-api
    newTag: dev-6abe0da
  - name: ghcr.io/douglasdossantos/mba-webapp-mvc
    newTag: dev-6abe0da
