// <auto-generated />
using System;
using MBA.Pagamentos.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MBA.Pagamentos.Data.Migrations
{
    [DbContext(typeof(FaturamentoDbContext))]
    [Migration("20260219182322_teste")]
    partial class teste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("MBA.Pagamentos.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("PagamentoId");

                    b.Property<string>("CodigoConfirmacaoPagamento")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("CodigoConfirmacaoPagamento");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataPagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataVencimento");

                    b.Property<Guid>("MatriculaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("MatriculaId");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("Valor");

                    b.HasKey("Id")
                        .HasName("PagamentosPK");

                    b.HasIndex("DataVencimento")
                        .HasDatabaseName("PagamentoDataVencimentoIDX");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("MBA.Pagamentos.Domain.Entities.Pagamento", b =>
                {
                    b.OwnsOne("MBA.Pagamentos.Domain.ValueObjects.DadosCartao", "Cartao", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CVV")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("CVVCartao");

                            b1.Property<string>("NomeTitular")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("NomeTitularCartao");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("TEXT")
                                .HasColumnName("NumeroCartao");

                            b1.Property<string>("Validade")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("TEXT")
                                .HasColumnName("ValidadeCartao");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamentos");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.OwnsOne("MBA.Pagamentos.Domain.ValueObjects.StatusPagamento", "StatusPagamento", b1 =>
                        {
                            b1.Property<Guid>("PagamentoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Status")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Status");

                            b1.HasKey("PagamentoId");

                            b1.ToTable("Pagamentos");

                            b1.WithOwner()
                                .HasForeignKey("PagamentoId");
                        });

                    b.Navigation("Cartao")
                        .IsRequired();

                    b.Navigation("StatusPagamento")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
